
trigger:
  none

variables:
# Docker Registry
  dockerRegistry: 'ashudevops'
  imageName1: 'ashu290996/FullStack-Blogging-App'

  imageTag: '$(Build.BuildId)'
  mavenCacheFolder: $(Pipeline.Workspace)/.m2/repository
  # SonarQube
  sonarQubeServiceConnection: 'sonarQube'
  sonarProjectKey: 'FullStack-Blogging-App'
  
  # Kubernetes
  kubernetesServiceConnection: 'k8s-prod-connection'
  stagingNamespace: 'staging'
  productionNamespace: 'production'
  
  # Build
  #vmImageName: 'ubuntu-latest'
  
  # Security Thresholds
  trivySeverity: 'HIGH,CRITICAL'
  owaspFailOnCVSS: 7

pool:
 name: default
stages:
    - stage: Package
      displayName: 'Build code'
      jobs:
          - job: mvnbuildcompile
            displayName: 'mvnbuildcompile'
            steps:
             - task: Cache@2
               displayName: 'Cache Maven Dependencies'
               inputs:
                  key: 'maven | "$(Agent.OS)" | pom.xml'
                  restoreKeys: |
                    maven | "$(Agent.OS)"
                  path: $(mavenCacheFolder)
          
             - script: |
                  mkdir -p $(mavenCacheFolder)
               displayName: Ensure Maven folder exists


             - task: Maven@4
               displayName: 'Maven Build'
               inputs:
                  mavenPomFile: 'pom.xml'
                  goals: 'clean package -Dskiptests'
                  options: '-Dmaven.repo.local=$(mavenCacheFolder) -DskipTests'
                  javaHomeOption: 'JDKVersion'

             - task: PublishPipelineArtifact@1
               inputs:
                targetPath: '$(Pipeline.Workspace)'
                artifact: 'twitter-app-0.0.3.jar'
                publishLocation: 'pipeline'
 
    - stage: SonarAnalysis
      displayName: 'SonarAnalysis'
      jobs:
        - job: SonarPrepare
          displayName: 'SonarPrepare'
          steps:

          - task: SonarQubePrepare@8
            continueOnError: true
            inputs:
              SonarQube: '$(sonarQubeServiceConnection)'
              scannerMode: 'cli'
              configMode: 'manual'
              cliProjectKey: 'FullStack-Blogging-App'
              cliProjectName: 'FullStack-Blogging-App'
              cliSources: 'FullStack-Blogging-App'
              # extraProperties: 
              #  sonar.projectKey=$(sonarProjectKey)
              #  sonar.projectName=$(sonarProjectKey)

          - task: SonarQubePublish@8
            inputs:
              pollingTimeoutSec: '300'


          - task: SonarQubeAnalyze@8
            inputs:
              jdkversion: 'JAVA_HOME_21_X64'

    - stage: OWASP
      displayName: 'OWASP'
      jobs:
        - job: OWASP
          displayName: 'OWASP dependency checker'
          steps:
        
          - task: dependency-check-build-task@6
            inputs:
              projectName: 'FullStack-Blogging-App'
              scanPath: 'pom.xml'
              format: 'HTML'
              uploadReports: true
              failOnCVSS: '7'
