
trigger:
  none

variables:
# Docker Registry
  dockerRegistry: 'ashudevops'
  imageTag: '$(Build.BuildId)'
  imageNAme1: 'ashu290996/FullStack-Blogging-App'
  mavenCacheFolder: $(Pipeline.Workspace)/.m2/repository
  # SonarQube
  sonarQubeServiceConnection: 'sonarQube'
  sonarProjectKey: 'FullStack-Blogging-App'
  
  # Kubernetes
  kubernetesServiceConnection: 'k8s-prod-connection'
  stagingNamespace: 'staging'
  productionNamespace: 'production'
  
  # Build
  #vmImageName: 'ubuntu-latest'
  
  # Security Thresholds
  trivySeverity: 'HIGH,CRITICAL'
  owaspFailOnCVSS: 7

pool:
 name: default
stages:
    - stage: Package
      displayName: 'Build code'
      jobs:
          - job: mvnbuildcompile
            displayName: 'mvnbuildcompile'
            steps:
             - task: Cache@2
               displayName: 'Cache Maven Dependencies'
               inputs:
                  key: 'maven | "$(Agent.OS)" | pom.xml'
                  restoreKeys: |
                    maven | "$(Agent.OS)"
                  path: $(mavenCacheFolder)
          
             - script: |
                  mkdir -p $(mavenCacheFolder)
               displayName: Ensure Maven folder exists


             - task: Maven@4
               displayName: 'Maven Build'
               inputs:
                  mavenPomFile: 'pom.xml'
                  goals: 'clean package -Dskiptests'
                  options: '-Dmaven.repo.local=$(mavenCacheFolder) -DskipTests'
                  javaHomeOption: 'JDKVersion'


             - task: PublishPipelineArtifact@1
               inputs:
                targetPath: '$(Pipeline.Workspace)'
                artifact: 'twitter-app-0.0.3.jar'
                publishLocation: 'pipeline'
             - task: Maven@4
               continueOnError: true
               displayName: 'Maven Deploy'
               inputs:
                  mavenPomFile: 'pom.xml'
                  goals: 'clean deploy -Dskiptests'
                  options: '-Dmaven.repo.local=$(mavenCacheFolder) -DskipTests'
                  javaHomeOption: 'JDKVersion'

 
    - stage: SonarAnalysis
      displayName: 'SonarAnalysis'
      jobs:
        - job: SonarPrepare
          displayName: 'SonarPrepare'
          steps:

          - task: SonarQubePrepare@8
            displayName: 'SonarQubePrepare'
            continueOnError: true
            inputs:
              SonarQube: '$(sonarQubeServiceConnection)'
              scannerMode: 'cli'
              configMode: 'manual'
              cliProjectKey: 'FullStack-Blogging-App-main'
              cliProjectName: 'FullStack-Blogging-App-main'
              cliSources: '$(System.DefaultWorkingDirectory)'
              extraProperties: 
                sonar.java.binaries=.
              #  sonar.projectKey=$(sonarProjectKey)
              #  sonar.projectName=$(sonarProjectKey)

          - task: SonarQubePublish@8
            continueOnError: true
            inputs:
              pollingTimeoutSec: '300'


          - task: SonarQubeAnalyze@8
            continueOnError: true
            inputs:
              jdkversion: 'JAVA_HOME_21_X64'

    - stage: OWASP
      displayName: 'OWASP'
      jobs:
        - job: OWASP
          displayName: 'OWASP dependency checker'
          steps:
        
          - task: dependency-check-build-task@6
            continueOnError: true
            inputs:
              projectName: 'FullStack-Blogging-App'
              scanPath: '$(System.DefaultWorkingDirectory)/pom.xml'
              format: 'HTML'
              uploadReports: true
              failOnCVSS: '7'
          

    - stage: TrivyScanJar
      displayName: 'TrivyScanJar' 
      jobs:
        - job: TrivyScanJar 
          displayName: 'Scanning Jar file for vulnerability'
          steps:

          - task: DownloadPipelineArtifact@2
            continueOnError: true
            inputs:
              buildType: 'current'
              artifactName: 'twitter-app-0.0.3.jar'
              targetPath: '$(Pipeline.Workspace)'

          - task: CmdLine@2
            continueOnError: true
            displayName: 'Scanning JAR files for vulnerabilities'
            inputs:
             script: |
              echo "=== Scanning JAR files for vulnerabilities ==="
              
              # Scan JAR files - Table format
              trivy fs /home/azureuser/myagent/_work/1/s/target/twitter-app-0.0.3.jar \
              --severity HIGH,CRITICAL \
              --format table \
              --output /home/azureuser/myagent/_work/1/s/target/trivy-jar-report.txt

              # Display results
              cat /home/azureuser/myagent/_work/1/s/target/trivy-jar-report.txt
              

    - stage: DockerImage
      displayName: 'DockerImage'
      jobs:
        - job: BuildPushImage
          displayName: 'Build and Push Docker Image'
          steps:

          - task: DownloadPipelineArtifact@2
            continueOnError: true
            inputs:
              buildType: 'current'
              artifactName: 'twitter-app-0.0.3.jar'
              targetPath: '$(Pipeline.Workspace)'

          - task: Docker@2
            inputs:
              containerRegistry: 'ashudevops'
              repository: '$(imageName1)'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(imageTag)
                latest
          

          - task: CmdLine@2
            continueOnError: true
            inputs:
             script: |
              trivy image --format table -o image.html $(imageNAme1):latest
              cat image.html
                  
    - stage: Deployonk8
      displayName: 'Deployonk8'
      jobs:
        - job: Deployonk8
          displayName: 'Deploying into k8'
          steps:

            - task: Kubernetes@1
              continueOnError: true
              displayName: 'Creating blog namepsace'
              inputs:
                connectionType: 'Kubernetes Service Connection'
                kubernetesServiceEndpoint: '$(kubernetesServiceConnection)'
                command: 'create'
                arguments: 'ns blog'
           
            - task: Kubernetes@1
              displayName: 'Apply deployment-service'
              inputs:
                connectionType: 'Kubernetes Service Connection'
                kubernetesServiceEndpoint: '$(kubernetesServiceConnection)'
                namespace: 'blog'
                command: 'apply'
                arguments: '-f deployment-service.yml'
 
            - task: Kubernetes@1
              continueOnError: true
              displayName: 'Wait for rollout to complete'
              inputs:
                connectionType: 'Kubernetes Service Connection'
                kubernetesServiceEndpoint: '$(kubernetesServiceConnection)'
                namespace: 'blog'
                command: 'rollout'
                arguments: ' status deployment/bloggingapp-deployment --timeout=300s'

            

            




