
trigger:
  none

variables:
# Docker Registry
  dockerRegistry: 'ashudevops'
  imageName1: 'ashu290996/wonderlustfrontend'
  imageName2: 'ashu290996/wonderlustbackened'
  imageTag: '$(Build.BuildId)'
  mavenCacheFolder: $(Pipeline.Workspace)/.m2/repository
  # SonarQube
  sonarQubeServiceConnection: 'sonarQube'
  sonarProjectKey: 'wonderlust'
  
  # Kubernetes
  kubernetesServiceConnection: 'k8s-prod-connection'
  stagingNamespace: 'staging'
  productionNamespace: 'production'
  
  # Build
  #vmImageName: 'ubuntu-latest'
  
  # Security Thresholds
  trivySeverity: 'HIGH,CRITICAL'
  owaspFailOnCVSS: 7

pool:
 name: default
stages:
    - stage: Package
      displayName: 'Build code'
      jobs:
          - job: mvnbuildcompile
            displayName: 'mvnbuildcompile'
            steps:
             - task: Cache@2
               displayName: 'Cache Maven Dependencies'
               inputs:
                  key: 'maven | "$(Agent.OS)" | pom.xml'
                  restoreKeys: |
                    maven | "$(Agent.OS)"
                  path: $(mavenCacheFolder)
          
             - script: |
                  mkdir -p $(mavenCacheFolder)
               displayName: Ensure Maven folder exists


             - task: Maven@4
               displayName: 'Maven Build'
               inputs:
                  mavenPomFile: 'pom.xml'
                  goals: 'clean package -Dskiptests'
                  options: '-Dmaven.repo.local=$(mavenCacheFolder) -DskipTests'
                  javaHomeOption: 'JDKVersion'

             - task: PublishPipelineArtifact@1
               inputs:
                targetPath: '$(Pipeline.Workspace)'
                artifact: 'twitter-app-0.0.3.jar'
                publishLocation: 'pipeline'

             